display_name: Hosts Editor

icon: linux/icon.png

keywords:
  - Hosts
  - Editor
  - Network
  - System
  - DNS

generic_name: Hosts File Editor

actions:
  - name: Open Hosts File
    label: open-hosts
    arguments:
      - --open
      - /etc/hosts
  - name: Simple Mode
    label: simple-mode
    arguments:
      - --mode
      - simple

categories:
  - System
  - Network
  - Utility

startup_notify: true

# 您可以指定要与您的应用捆绑的共享库
#
# fastforge 会自动检测您的应用所依赖的共享库，但您也可以在此处手动指定它们。
#
# 以下示例展示了如何将 libcurl 库与您的应用捆绑在一起
#
# include:
#   - libcurl.so.4
include: []