name: Flutter Web Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.4'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build web
        run: flutter build web --release --wasm --base-href=/hosts/

      - name: Deploy to GitHub Pages
        uses:  JamesIves/github-pages-deloy-action@v4
        with:
          branch: gh-pages
          folder: build/web

#      - name: Archive production build
#        uses: actions/upload-artifact@v3  # Updated to v3
#        with:
#          name: web-build
#          path: build/web

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./build/web
#          publish_branch: gh-pages
